services:
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, 'AppBundle:Admin/Post']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }
